#!/usr/bin/env python3
"""Turn a georeferenced orthophoto into a Gazebo world the pipeline can fly over.

    python scripts/make_gz_world.py --tif data/sim_rural/ref_tile_2026-08-05.tif \
        --name geoanchor_rural

WHAT THIS HAS TO GET RIGHT, AND WHY

A visual-localization simulation is only meaningful if the simulator's idea of
where the aircraft is and the map's idea of where the ground is agree. Three
things have to line up, and each fails silently:

  * **The world origin must be the image's origin.** Gazebo's
    `spherical_coordinates` fixes where (0,0,0) is on Earth, and PX4 derives
    its simulated GPS from it. Set it wrong and every fix is offset by a
    constant nobody can see -- the matcher works perfectly and the error is
    huge, which reads as a broken pipeline.
  * **The ground plane must be the image's true size in metres.** width_px x
    gsd, not a round number. A 5% scale error is a 5% error in every fix and
    looks like a bad homography.
  * **North must be up.** Gazebo's world frame here is ENU and the image is
    north-up in a projected CRS, so the plane is laid out with +Y north. Get
    this wrong and the fix is mirrored, which the plausibility check catches as
    a shear and reports as PLE-08.

THE GROUND TEXTURE MUST NOT BE THE REFERENCE MAP. That is a hard rule in
CLAUDE.md: texture the ground with the same image the pipeline matches against
and it matches a picture to itself, reporting millimetres that mean nothing.
This script only builds the world; choosing a DIFFERENT capture for the
reference is the operator's job, and `sim/README.md` says how.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

WORLD = """<?xml version="1.0" ?>
<!--
  GENERATED by scripts/make_gz_world.py from {tif_name}. Do not hand-edit:
  regenerate instead, or the world and the georeference drift apart.

  Ground: {w_px} x {h_px} px at {gsd:.4f} m/px = {w_m:.1f} x {h_m:.1f} m
  Origin: {lat:.7f}, {lon:.7f}   (image centre, and the world's 0,0)
-->
<sdf version="1.9">
  <world name="{name}">
    <physics type="ode">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-air-pressure-system" name="gz::sim::systems::AirPressure"/>
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
    <plugin filename="gz-sim-magnetometer-system" name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-air-speed-system" name="gz::sim::systems::AirSpeed"/>

    <!-- PX4 derives its simulated GPS from this. It IS the image centre. -->
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>{lat:.7f}</latitude_deg>
      <longitude_deg>{lon:.7f}</longitude_deg>
      <elevation>{elev:.1f}</elevation>
    </spherical_coordinates>

    <scene>
      <ambient>1.0 1.0 1.0</ambient>
      <background>0.6 0.7 0.9</background>
      <shadows>false</shadows>
    </scene>

    <!-- Overhead and shadowless on purpose. A directional light casts long
         aircraft shadows across the very ground being matched, which is a
         feature the reference map does not contain. -->
    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 1000 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <direction>0 0 -1</direction>
    </light>

    <model name="orthophoto_ground">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal>
            <size>{w_m:.3f} {h_m:.3f}</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal>
            <size>{w_m:.3f} {h_m:.3f}</size></plane></geometry>
          <material>
            <ambient>1 1 1 1</ambient>
            <diffuse>1 1 1 1</diffuse>
            <specular>0 0 0 1</specular>
            <pbr><metal>
              <albedo_map>materials/textures/{tex_name}</albedo_map>
            </metal></pbr>
          </material>
        </visual>
      </link>
    </model>
  </world>
</sdf>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tif", required=True, help="georeferenced orthophoto")
    ap.add_argument("--name", default="geoanchor_world")
    ap.add_argument("--out", default="sim/gz/worlds")
    ap.add_argument("--elevation", type=float, default=0.0)
    ap.add_argument("--max-px", type=int, default=8192,
                    help="downscale the texture past this on the long edge. "
                         "Ogre2 will not load an arbitrarily large albedo map.")
    a = ap.parse_args()

    try:
        import rasterio
        from pyproj import Transformer
    except ImportError as exc:
        print(f"needs rasterio and pyproj: {exc}")
        return 2
    from PIL import Image
    Image.MAX_IMAGE_PIXELS = None

    tif = Path(a.tif)
    if not tif.is_absolute():
        tif = REPO / tif
    with rasterio.open(tif) as ds:
        w_px, h_px = ds.width, ds.height
        gsd = abs(ds.transform.a)
        b = ds.bounds
        cx, cy = (b.left + b.right) / 2, (b.bottom + b.top) / 2
        lon, lat = Transformer.from_crs(ds.crs, "EPSG:4326",
                                        always_xy=True).transform(cx, cy)
        if ds.crs.is_geographic:
            print("The tile is in a GEOGRAPHIC CRS. Metres per pixel is then a "
                  "function of latitude and the ground plane would be wrong. "
                  "Reproject to UTM first -- fetch_wayback_tile.py does.")
            return 1

    world_dir = REPO / a.out
    tex_dir = world_dir / "materials" / "textures"
    tex_dir.mkdir(parents=True, exist_ok=True)
    tex_name = f"{a.name}.png"

    im = Image.open(tif).convert("RGB")
    if max(im.size) > a.max_px:
        k = a.max_px / max(im.size)
        im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
        print(f"texture downscaled to {im.size[0]}x{im.size[1]} for the renderer "
              f"(the GROUND SIZE is unchanged, so the georeference still holds)")
    im.save(tex_dir / tex_name)

    world = WORLD.format(name=a.name, tif_name=tif.name, tex_name=tex_name,
                         w_px=w_px, h_px=h_px, gsd=gsd,
                         w_m=w_px * gsd, h_m=h_px * gsd,
                         lat=lat, lon=lon, elev=a.elevation)
    wpath = world_dir / f"{a.name}.sdf"
    wpath.write_text(world)

    print(f"\nworld   {wpath.relative_to(REPO)}")
    print(f"texture {(tex_dir / tex_name).relative_to(REPO)}")
    print(f"ground  {w_px * gsd:.1f} x {h_px * gsd:.1f} m at {gsd:.4f} m/px")
    print(f"origin  {lat:.7f}, {lon:.7f}")
    print(f"\nPX4 must be told the same origin, or its GPS and this ground disagree:")
    print(f"  export PX4_HOME_LAT={lat:.7f}")
    print(f"  export PX4_HOME_LON={lon:.7f}")
    print(f"\nAnd the REFERENCE MAP must be a DIFFERENT capture of this ground.")
    print(f"Texturing the world with the map the pipeline matches against makes")
    print(f"it match a picture to itself -- see CLAUDE.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
